### ISSUE TITLE
WebApp Server disconnection error in Windows 10

### ISSUE THREAD

**Issue by PrashantR-79** [TomorrowsCities/tomorrowscities#11]
[WebApp Solara error log Windows 10.txt](https://github.com/TomorrowsCities/tomorrowscities/files/13612377/WebApp.Solara.error.log.Windows.10.txt)

**Comment by hkayabilisim** [comment]
Hi Prashant!

Can you try the workaround mentioned below and see if that helps.

https://serverfault.com/questions/204150/sometimes-powershell-stops-sending-output-until-i-press-enter-why

**Comment by PrashantR-79** [comment]
Thank you Huseyin! I will try this solution and let you know.

**Comment by PrashantR-79** [comment]
Huseyin, I tried unchecking the 'Quick Edit Mode' and 'Insert Mode' in the command prompt properties as suggested, and it still does not solve the 'Server disconnection' issue.

**Comment by hkayabilisim** [comment]
I've tested the webapp on Windows 11 (Virtual environment under Mac) for some time and I haven't seen this error once. Very strange! I'll test Windows 10. Have you find a chance to test outside of your environment? This is important because we should isolate the problem. Is it something specific to your local OS environment or not? Please let us know when you test on other environments.

**Comment by PrashantR-79** [comment]
Huseyin, I tested the WebApp (online) in Windows 11 and Linux Mint 21.2. The app ran smoothly without any issues there. The problem seems to be in Windows 10. I tested the app in 3 laptops with windows 10, and I got the server disconnection issue.

**Comment by PrashantR-79** [comment]
It seems the issues is caused by anti-virus software blocking the app. The App runs smoothly in Windows 10 as well after disabling the antivirus..

**Comment by hkayabilisim** [comment]
Ok, at least we have a clue now. The next step should be opening an issue on https://github.com/widgetti/solara. But for this, can you recreate the issue by using one of the hello world examples of solara.dev and take a screenshot of the popup window? We should prepare a smallest set of conditions where this error occurs so that the dev team of solara can fix it easily.  By the way which antivirus software are you using?

**Comment by PrashantR-79** [comment]
All the laptops I used had Kaspersky antivirus installed. I did try to recreate this issue using a simple example (attached), but the server disconnection never happens here. I run this script as: solara run test.py
[test.py.txt](https://github.com/TomorrowsCities/tomorrowscities/files/13711772/test.py.txt)
